# Generated by Django 5.2.4 on 2025-07-09 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlog',
            name='action',
            field=models.CharField(choices=[('start_voting', 'Started Voting'), ('stop_voting', 'Stopped Voting'), ('show_results', 'Showed Results'), ('hide_results', 'Hid Results'), ('generate_ids', 'Generated Voting IDs'), ('create_project', 'Created Project'), ('edit_project', 'Updated Project'), ('delete_project', 'Deleted Project'), ('login', 'Admin Login'), ('logout', 'Admin Logout')], max_length=20),
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
