# Generated by Django 5.2.4 on 2025-07-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_alter_adminlog_action_alter_adminlog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('education_learning', 'Education & Learning Technology'), ('agriculture', 'Agriculture Technology'), ('sports', 'Sports Technology'), ('legal_cybersecurity', 'Legal & Cybersecurity AI'), ('health_wellness', 'Health & Wellness AI'), ('financial_business', 'Financial & Business Innovations'), ('public_services', 'Public Services & Information'), ('human_resources', 'Human Resources and Career Development'), ('smart_living', 'Smart Living and Sustainability'), ('language_ai', 'Language and Advanced AI Research')], default='education_learning', max_length=30),
        ),
    ]
